# Generated by Django 4.2.6 on 2023-10-28 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_sku', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=150)),
                ('codigo_sublinea', models.CharField(max_length=15)),
                ('factor_compra', models.IntegerField()),
                ('factor_reparto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_documento', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GruposProveedor',
            fields=[
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_grupo', models.CharField(max_length=15)),
                ('grupo_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Inventarios',
            fields=[
                ('inventario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_inventario', models.DateTimeField()),
                ('nro_inventario', models.IntegerField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('total_inventario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField()),
                ('creado_por', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField()),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='LineasArticulos',
            fields=[
                ('linea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_linea', models.CharField(max_length=15)),
                ('linea_descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.gruposproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('marca_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_marca', models.CharField(max_length=14)),
                ('marca_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('unidad_medida_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unidad_nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('sucursal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SublineasArticulos',
            fields=[
                ('sublinea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo_sublinea', models.CharField(max_length=15)),
                ('sublinea_descripcion', models.CharField(max_length=100)),
                ('linea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lineasarticulos')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_personal', models.CharField(max_length=100)),
                ('direccion_personal', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=1)),
                ('nro_documento', models.CharField(max_length=11)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='lineasarticulos',
            name='responsable_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.personal'),
        ),
        migrations.CreateModel(
            name='ItemsInventario',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nro_item', models.IntegerField()),
                ('stock_fisico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devoluciones_pendientes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_unidades_stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulos')),
                ('inventario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventarios')),
            ],
        ),
        migrations.AddField(
            model_name='inventarios',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.personal'),
        ),
        migrations.AddField(
            model_name='inventarios',
            name='sucursal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sucursales'),
        ),
        migrations.AddField(
            model_name='gruposproveedor',
            name='responsable_grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.personal'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.gruposproveedor'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='linea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.lineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sublinea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sublineasarticulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='unidad_medida_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.unidadesmedida'),
        ),
    ]
