# Generated by Django 4.2.6 on 2023-10-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.RenameModel(
            old_name='GruposProveedor',
            new_name='GrupoProveedor',
        ),
        migrations.RenameModel(
            old_name='Inventarios',
            new_name='Inventario',
        ),
        migrations.RenameModel(
            old_name='ItemsInventario',
            new_name='ItemInventario',
        ),
        migrations.RenameModel(
            old_name='LineasArticulos',
            new_name='LineaArticulo',
        ),
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
        migrations.RenameModel(
            old_name='SublineasArticulos',
            new_name='SublineaArticulo',
        ),
        migrations.RenameModel(
            old_name='Sucursales',
            new_name='Sucursal',
        ),
        migrations.RenameModel(
            old_name='UnidadesMedida',
            new_name='UnidadMedida',
        ),
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
