# Generated by Django 4.2.6 on 2023-10-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_articulos_articulo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
