# Generated by Django 4.2.6 on 2023-10-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_personal_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoproveedor',
            old_name='grupo',
            new_name='id',
        ),
    ]
