# Generated by Django 4.2.6 on 2023-10-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_grupo_grupoproveedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublineaarticulo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
