# Generated by Django 4.2.6 on 2023-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_sublineaarticulo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='responsable',
            new_name='personal',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('C', 'Closed')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('empresa', 'sucursal', 'fecha_inventario')},
        ),
    ]
