# Generated by Django 4.2.6 on 2023-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_responsable_inventario_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name=['%I:%H %p']),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
