# Generated by Django 4.2.6 on 2023-10-31 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_inventario_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('fecha_inventario', 'empresa', 'sucursal')},
        ),
        migrations.AddField(
            model_name='inventario',
            name='cerrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='hora_fin',
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
    ]
