# Generated by Django 4.2.6 on 2023-11-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
