# Generated by Django 4.2.6 on 2023-11-01 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventario',
            name='responsable_linea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='iteminventario',
            unique_together={('inventario', 'articulo', 'responsable_linea')},
        ),
    ]
